import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="min-w-[375px] mx-auto p-4 lg:max-w-[1140px]  ">
          <header className="mb-8">
            <nav>
              <ul className="flex justify-between items-center lg:justify-evenly ">
                <li className="item">
                  <Link className="nav_link" href={"/"}>
                    SSR
                  </Link>
                </li>
                <li className="item">
                  <Link className="nav_link" href={"/post/1"}>
                    SSG
                  </Link>
                </li>
                <li className="item">
                  <Link className="nav_link" href={"/csr"}>
                    CSR
                  </Link>
                </li>
                <li className="item">
                  <Link className="nav_link" href={"/isr"}>
                    ISR
                  </Link>
                </li>
              </ul>
            </nav>
          </header>

          {children}
        </div>
      </body>
    </html>
  );
}
